// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLHQs3r9z-yiqy9-qv6Bt6kZt7YdDQmGA',
    appId: '1:910749107065:web:3b2e6fd299a36c861125a8',
    messagingSenderId: '910749107065',
    projectId: 'fleetmonitor360-58b46',
    authDomain: 'fleetmonitor360-58b46.firebaseapp.com',
    storageBucket: 'fleetmonitor360-58b46.firebasestorage.app',
    measurementId: 'G-Z5M5EJZB6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfgT5REOlgh5ZDAe0XhZwL1uL7zcK4XrY',
    appId: '1:910749107065:android:d43578847b16c28d1125a8',
    messagingSenderId: '910749107065',
    projectId: 'fleetmonitor360-58b46',
    storageBucket: 'fleetmonitor360-58b46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVqPo0eKlL6c-7FAZygYFZZkh7wfE7wY',
    appId: '1:910749107065:ios:f61aaa655e0ad9a11125a8',
    messagingSenderId: '910749107065',
    projectId: 'fleetmonitor360-58b46',
    storageBucket: 'fleetmonitor360-58b46.firebasestorage.app',
    iosBundleId: 'com.globynix.fleetMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVqPo0eKlL6c-7FAZygYFZZkh7wfE7wY',
    appId: '1:910749107065:ios:f61aaa655e0ad9a11125a8',
    messagingSenderId: '910749107065',
    projectId: 'fleetmonitor360-58b46',
    storageBucket: 'fleetmonitor360-58b46.firebasestorage.app',
    iosBundleId: 'com.globynix.fleetMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLHQs3r9z-yiqy9-qv6Bt6kZt7YdDQmGA',
    appId: '1:910749107065:web:f358b12608d4a9621125a8',
    messagingSenderId: '910749107065',
    projectId: 'fleetmonitor360-58b46',
    authDomain: 'fleetmonitor360-58b46.firebaseapp.com',
    storageBucket: 'fleetmonitor360-58b46.firebasestorage.app',
    measurementId: 'G-NQ9P93R2HY',
  );
}
